# Файл продублирован внутри composeApp, чтобы приложение находило конфигурацию
# и при запуске из корня lab7, и при запуске из каталога composeApp.

window.width=560
window.height=780
ui.style=lowVisionDark
ui.background=#121212
ui.font.family=SansSerif
ui.font.size=20
db.url=jdbc:sqlite:calculator.db
db.user=calculator
db.password=
